export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as Hero } from './Hero/Hero';
export { default as Specials } from './Specials/Specials';
export { default as FoodCard } from './FoodCard/FoodCard';
export { default as Testimonials } from './Testimonials/Testimonials';
export { default as About } from './About/About';
export { default as Form } from './Form/Form';
export { default as ConfirmedBooking } from './ConfirmedBooking/ConfirmedBooking';
